"""
LangGraph state definition for the multi-agent research assistant.

ResearchState flows through the graph, accumulating search results
via operator.add on raw_context and tracking loop iterations.
"""

import operator
from typing import Annotated, TypedDict


class ResearchState(TypedDict):
    """Shared state passed between all agents in the research graph."""

    # The user's original research query
    query: str

    # Search terms generated by the query-planning agent
    search_queries: list[str]

    # Accumulated scraped markdown content (appended across loops)
    raw_context: Annotated[list[str], operator.add]

    # Current synthesized report produced by the writer agent
    draft_summary: str

    # Feedback from the validation / critique agent
    revision_notes: str

    # Counter to cap routing loops and prevent runaway iterations
    iteration_count: int
